file5.txt:
    echo "This is file 5" > file5.txt

file4.txt: file3.txt file5.txt
    echo "This is file 4" > file4.txt

file3.txt: file1.txt file2.txt
    echo "This is file 3" > file3.txt

file2.txt:
    echo "This is file 2" > file2.txt

file1.txt:
    echo "This is file 1" > file1.txt
